workflowVersion: 1.0.0
sources:
    my-first-source:
        inputs:
            - location: http://api.localhost:8888/
targets:
    my-first-target:
        target: typescript
        source: my-first-source
