workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-first-source:
        inputs:
            - location: https://api.dub.co
targets:
    my-first-target:
        target: typescript
        source: my-first-source
        codeSamples:
          output: codeSamples.json
        publish:
            npm:
                token: $npm_token
